name: 2DTS
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - setuptools<82
  - wheel
  - packaging
  - ninja
  - numpy
  - opencv
  - scipy
  - scikit-image
  - scikit-learn
  - matplotlib
  - cycler
  - pillow
  - plyfile
  - pyyaml
  - shapely
  - tqdm
  - trimesh
  - igl
  - open3d
  - tensorboard
  - oss2
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.11.0+cu128
      - torchvision==0.26.0+cu128
      - torchmetrics
      - viser
