lr_delay_steps: &LR_DELAY_STEPS 2_000
lr_delay_mult: &LR_DELAY_MULT 1.0
lr_max_steps: &LR_MAX_STEPS 30_000
total_iter: &TOTAL_ITER 30_000

dataset:
    type: "NerfSynthetic"
    local_dir: null
    scene_id: null
    background: "random"
    test_background: "white"
    num_workers: 10
    cache_on_device: True # decode images once and serve cameras from the GPU instead of loader workers

    pcd_path: "points3d.ply"
    train_target_res: null
    test_target_res: null
    hold_test_set: True

model:
    max_sh_degree: 3
    use_color_affine: False
    back_culling: False
    use_vertex_color: False
    gamma_rescale: True
    sort_level: 0 # 0: per triangle, 1: per tile, 2: per pixel

    sampling:
        sample_method: "direct" # "random" | "grid" | "direct"
        init_opacity: 0.1 # float | "random"

    optimizer:
        vertex:
            v_init: 0.0012
            v_final: 0.00002
            delay_steps: *LR_DELAY_STEPS
            delay_mult: *LR_DELAY_MULT
            max_steps: *LR_MAX_STEPS

        opacity:
            v_init: 0.05
            v_final: 0.005
            delay_steps: *LR_DELAY_STEPS
            delay_mult: *LR_DELAY_MULT
            max_steps: *LR_MAX_STEPS

        f_dc:
            v_init: 0.001
            v_final: 0.001
            delay_steps: *LR_DELAY_STEPS
            delay_mult: *LR_DELAY_MULT
            max_steps: *LR_MAX_STEPS

        f_rest:
            v_init: 0.0002
            v_final: 0.0002
            delay_steps: *LR_DELAY_STEPS
            delay_mult: *LR_DELAY_MULT
            max_steps: *LR_MAX_STEPS

    model_update:
        statistic:
            start_iter: 400
            end_iter: 15_000

        densification:
            start_iter: 500
            end_iter: 15_000
            interval_iter: 100
            grad_threshold_init: 0.0002
            grad_threshold_final: 0.0002
            target_point_num: null
            grow_ratio: 0.04
            max_grow_ratio: 0.01
            min_view_count: 10
            # split_scale_threshold: 0.01 # unit: m, proportional to scene extent
            split_radii_threshold: 5 # unit: pixel
            split_num: 4 # 2 | 3 | 4

        opacity_pruning:
            start_iter: 3_000
            end_iter: 15_000
            hold_iter: 15_000
            interval_iter: 200
            opacity_threshold_init: 0.005
            opacity_threshold_final: 0.005

        scale_pruning:
            start_iter: 3000
            end_iter: 15_000
            interval_iter: 200
            radii_threshold: -1 # int means pixel, -1 means max(image_width, image_height), float means fraction of max(image_width, image_height)
            scale_threshold: 0.5 # unit: m, proportional to scene extent

        opacity_reset:
            start_iter: 0
            end_iter: 15_000
            interval_iter: 3000
            reset_value: 0.01

        sh_schedule:
            one_up_iters: [1000, 2000, 3000]

trainer:
    output_dir: "outputs/NerfSynthetic/VanillaTS"
    clean_output_dir: False # clean output_dir before training
    detect_anomaly: False
    seed: null
    use_tensorboard: True
    save_train_img: True
    save_eval_img: False

    start_checkpoint: null
    start_pointcloud: null
    initial_eval: False
    iterations: *TOTAL_ITER
    batch_size: 1
    log_interval_iter: 200
    eval_interval_iter: 2_000
    histogram_interval_iter: 5_000
    save_interval_iter: 0
    ckpt_interval_iter: 0
    save_iterations: [*TOTAL_ITER]
    checkpoint_iterations: [*TOTAL_ITER]
    save_mesh_iterations: []

    train_background: null # "white" | "black" | "random" | null, if null, use dataset background
    eval_background: null # "white" | "black" | "random" | null, if null, use dataset background
    train_alpha_mask: False
    eval_alpha_mask: False

    w_L1: 0.8
    w_L2: 0.0
    w_ssim: 0.2
    w_dog: 0.0
    
    smoothness_loss:
        w_image: 0.0
        w_normal: 0.0
        w_depth: 0.0
        start_iter: 3_000
    geometry_loss:
        w_geometry: 0.0
        scale_factor: null
        start_iter: 3_000
    distortion_loss:
        w_distortion: 0.0
        start_iter: 3_000

    w_scaling_reg: 0.0
    w_affine_reg: 0.0
    opacity_reg:
        w_opacity_reg: 0.0 # -0.01
        start_iter: 0
        type: "linear" # "quad" | "linear"
    vertex_reg:
        w_vertex_reg: 0.0
        start_iter: 0
        interval_iter: 10

    eval_save_img_count: 3
    histogram_sample_num: 10_000
