#pragma once

#include <torch/extension.h>
#include <tuple>

std::tuple<int, torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor>
rasterizeHybridForward(
    const int image_width,
    const int image_height,
    const float tan_fovx,
    const float tan_fovy,
    const torch::Tensor &viewmatrix,
    const torch::Tensor &projmatrix,
    const torch::Tensor &full_projmatrix,
    const torch::Tensor &campos,
    const int tri_sh_degree,
    const int gau_sh_degree,
    const float tri_gamma,
    const float gau_gamma,
    const float ambient_intensity,
    const torch::Tensor &light_color,
    const torch::Tensor &light_dir,
    const float light_intensity,
    const float background_depth,
    const torch::Tensor &background,
    const torch::Tensor &vertex,
    const torch::Tensor &shs,
    const torch::Tensor &feature,
    const torch::Tensor &tri_uv,
    const torch::Tensor &tri_texture,
    const torch::Tensor &opacity,
    const bool back_culling,
    const bool rich_info,
    const int sort_level,
    const torch::Tensor &means3D,
    const torch::Tensor &gaussian_shs,
    const torch::Tensor &gaussian_colors,
    const torch::Tensor &gaussian_opacity,
    const torch::Tensor &gaussian_scales,
    const torch::Tensor &gaussian_rotations,
    const torch::Tensor &gaussian_cov3D_precomp,
    const bool gaussian_prefiltered,
    const bool debug = false);

std::tuple<torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor>
rasterizeHybridBackwardNotImplemented(
    const float tan_fovx,
    const float tan_fovy,
    const torch::Tensor &viewmatrix,
    const torch::Tensor &projmatrix,
    const torch::Tensor &campos,
    const int tri_sh_degree,
    const float gamma,
    const float background_depth,
    const torch::Tensor &background,
    const torch::Tensor &vertex,
    const torch::Tensor &shs,
    const torch::Tensor &feature,
    const torch::Tensor &opacity,
    const int num_rendered,
    const torch::Tensor &radii,
    const torch::Tensor &final_feature,
    const torch::Tensor &final_depth,
    const torch::Tensor &final_normal,
    const torch::Tensor &final_distortion,
    const torch::Tensor &geometryBuffer,
    const torch::Tensor &binningBuffer,
    const torch::Tensor &imageBuffer,
    const torch::Tensor &dL_dout_feature,
    const torch::Tensor &dL_dout_depth,
    const torch::Tensor &dL_dout_normal,
    const torch::Tensor &dL_dout_distortion,
    const bool back_culling,
    const bool rich_info,
    const int sort_level,
    const bool debug = false);
