#pragma once

#include <cuda_runtime.h>
#include <device_launch_parameters.h>
#include <cstdint>

namespace FORWARD
{
void preprocessTriangles(
    int W, int H, int P, int D, int M,
    float gamma,
    bool use_shs,
    bool use_vertex_color,
    bool back_culling,
    dim3 grid,
    const float *viewmatrix,
    const float *projmatrix,
    const float *campos,
    const float *vertex,
    const float *shs,
    int *radii,
    float3 *v1_view,
    float3 *v2_view,
    float3 *v3_view,
    float3 *normal_view,
    float *depth,
    float *tri_rgb,
    bool *clamped,
    uint32_t *tiles_touched,
    uint2 *rect_min,
    uint2 *rect_max);

void preprocessGaussians(
    int W, int H, int P, int D, int M,
    float tan_fovx, float tan_fovy,
    float focal_x, float focal_y,
    float scale_modifier,
    bool prefiltered,
    bool use_shs,
    bool use_cov_precomp,
    dim3 grid,
    const float *viewmatrix,
    const float *projmatrix,
    const float *full_projmatrix,
    const float *campos,
    const float *means3D,
    const float *gaussian_shs,
    const float *gaussian_colors,
    const float *gaussian_opacity,
    const float *gaussian_scales,
    const float *gaussian_rotations,
    const float *gaussian_cov3D_precomp,
    int *radii,
    float2 *means2D,
    float *depths,
    float *cov3Ds,
    float4 *conic_opacity,
    float *feature,
    bool *clamped,
    uint32_t *tiles_touched,
    uint2 *rect_min,
    uint2 *rect_max);

void renderHybrid(
    dim3 grid,
    dim3 block,
    int W,
    int H,
    int C,
    int P_tri,
    float tri_gamma,
    float gau_gamma,
    float ambient_intensity,
    const float *light_color,
    const float *light_dir,
    float light_intensity,
    bool rich_info,
    bool tri_use_texture,
    bool tri_use_vertex_color,
    float tan_fovx,
    float tan_fovy,
    const uint2 *ranges,
    const uint32_t *point_list,
    const float3 *tri_v1,
    const float3 *tri_v2,
    const float3 *tri_v3,
    const float3 *tri_n,
    const float *tri_feature,
    const float2 *tri_uv,
    const float *tri_texture,
    int tri_tex_H,
    int tri_tex_W,
    const float *tri_opacity,
    const float2 *gau_xy,
    const float4 *gau_conic,
    const float *gau_feature,
    const float *gau_depth,
    const float *background,
    float background_depth,
    float *final_Ts,
    uint32_t *n_contribs,
    float *out_feature,
    float *out_depth,
    float *out_normal,
    float *out_distort,
    float *contrib_sum,
    float *contrib_max);

void renderHybridResort(
    dim3 grid,
    dim3 block,
    int W,
    int H,
    int C,
    int P_tri,
    float tri_gamma,
    float gau_gamma,
    float ambient_intensity,
    const float *light_color,
    const float *light_dir,
    float light_intensity,
    bool rich_info,
    bool tri_use_texture,
    bool tri_use_vertex_color,
    float tan_fovx,
    float tan_fovy,
    const uint2 *ranges,
    const uint32_t *point_list,
    const float3 *tri_v1,
    const float3 *tri_v2,
    const float3 *tri_v3,
    const float3 *tri_n,
    const float *tri_feature,
    const float2 *tri_uv,
    const float *tri_texture,
    int tri_tex_H,
    int tri_tex_W,
    const float *tri_opacity,
    const float2 *gau_xy,
    const float4 *gau_conic,
    const float *gau_feature,
    const float *gau_depth,
    const float *background,
    float background_depth,
    float *final_Ts,
    uint32_t *n_contribs,
    float *out_feature,
    float *out_depth,
    float *out_normal,
    float *out_distort,
    float *contrib_sum,
    float *contrib_max);
}
